name: geoapps-docs

channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.0.1
  - ipywidgets
  - ipykernel
  - pandoc=3.1.3
  - pip:
    - numpydoc
    - jinja2==3.0.3
    - sphinx==3.5.4
    - sphinx_issues
    - nbsphinx
    - sphinx-gallery==0.10
    - jupyter_sphinx
    - plotly==4.9.0
