name: geoapps-docs

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=21.0.1
  - ipywidgets
  - ipykernel
  - pip:
    - geoh5py==0.1.4
    - numpydoc
    - sphinx==3.5.4
    - sphinx_issues
    - nbsphinx
    - sphinx-gallery
    - jupyter_sphinx
    - plotly==4.9.0
