# This workflow will comment the PR with the JIRA issue summary
# if a JIRA issue number is detected in the branch name or title

name: Add JIRA issue summary

on:
  pull_request:
    types: [opened]

jobs:
  add_jira_summary:
    runs-on: ubuntu-latest

    steps:
    - name: JIRA Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Find JIRA issue key
      id: find_jira_key
      uses: atlassian/gajira-find-issue-key@v2.0.2
      with:
        string: ${{ github.head_ref}} ${{ github.event.pull_request.title }}
        from: ""
    - name: Get JIRA summary
      id: get_jira_summary
      if: ${{ steps.find_jira_key.outputs.issue }}
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_BASIC_AUTH: ${{ secrets.JIRA_BASIC_AUTH }}
      run: >
        curl -sS -X GET
        -H "Authorization: Basic $JIRA_BASIC_AUTH"
        -H "Content-Type: application/json"
        "$JIRA_BASE_URL/rest/api/2/issue/${{ steps.find_jira_key.outputs.issue }}"
        | echo "::set-output name=summary::$(jq -r '.fields.summary')"
    - name: Add comment
      if: ${{ steps.find_jira_key.outputs.issue }}
      run: >
        jq -nc '{
        "body":
        "**${{ steps.find_jira_key.outputs.issue }} - ${{ steps.get_jira_summary.outputs.summary }}** \n
        ${{ github.event.pull_request.body }}"
        }' |
        curl -sS -X POST -d @-
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
        -H "Content-Type: application/json"
        "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }}"
        > /dev/null
